version: '3.7'

services: 

  #Backend API
  smart-brain-api:
    container_name: backend
    command: npm start
    working_dir: /usr/src/smart-brain-api
    ports: ["3000:3000"]
    build: ./ 
    volumes: ["./:/usr/src/smart-brain-api"]
    environment: 
      POSTGRES_URL: postgres://sally:secret@postgres:5432/smart-brain-docker
      REDIS_HOST: redis://redis
    links: ["postgres","redis"]
    # If not from a focker file
    # image: node:11.8.0
    # environment: 
    # links:
    #   post..
    

    # PostgreSQL 
  postgres:
    container_name: my_postgres
    restart: always
    environment: 
      POSTGRES_USER: sally
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: smart-brain-docker
    build: ./postgres
    ports: ['5432:5432']

  # Redis
  redis:
    image: redis
    ports: ['6379:6379']
