
GET http://localhost:3000/profile/1

###

POST http://localhost:3000/profile/1 HTTP/1.1
content-Type: application/json

{
    "formInput": {
    "name":"am2"
    }
}

### Signin-Auth
POST http://localhost:3000/signin HTTP/1.1
Content-Type: application/json

{
    "email":"am@am.com",
    "password":"a"
}

### PRE-Authorized signin
POST http://localhost:3000/signin HTTP/1.1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFtQGFtLmNvbSIsImlhdCI6MTU1ODAyOTQzMywiZXhwIjoxNTU4MjAyMjMzfQ.jL-JfT6vbWXM2qkL2yWeOw2EqgvEazbWYbCQkrQP118

{
    "email":"am@am.com",
    "password":"a"
}